// Professional PDF report via jsPDF + autotable.
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

const TEAL = [14, 116, 144]
const DARK = [15, 23, 42]

export function generatePDF({ input, result }) {
  const d = new jsPDF({ unit: 'pt', format: 'a4' })
  const W = d.internal.pageSize.getWidth()
  let y = 0

  // Header band
  d.setFillColor(...TEAL)
  d.rect(0, 0, W, 90, 'F')
  d.setTextColor(255, 255, 255)
  d.setFont('helvetica', 'bold'); d.setFontSize(22)
  d.text('RWH Assess TN', 40, 40)
  d.setFont('helvetica', 'normal'); d.setFontSize(11)
  d.text('Rainwater Harvesting Potential Assessment Report', 40, 62)
  d.setFontSize(9)
  d.text('Tamil Nadu', W - 40, 40, { align: 'right' })
  d.text(new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }), W - 40, 58, { align: 'right' })

  y = 120
  d.setTextColor(...DARK)

  section(d, 'Property Details', y); y += 8
  autoTable(d, {
    startY: y,
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 3 },
    body: [
      ['Owner Name', input.ownerName || '—'],
      ['Property Name', input.propertyName || '—'],
      ['Location', `${input.village ? input.village + ', ' : ''}${input.taluk || ''}${input.taluk ? ', ' : ''}${input.district}`],
      ['Roof Type', input.roofType],
      ['Soil Type', input.soilType],
    ],
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 160, textColor: TEAL } },
  })
  y = d.lastAutoTable.finalY + 24

  section(d, 'Assessment Summary', y); y += 8
  autoTable(d, {
    startY: y,
    theme: 'grid',
    headStyles: { fillColor: TEAL, textColor: 255, fontSize: 10 },
    styles: { fontSize: 10, cellPadding: 5 },
    head: [['Parameter', 'Value']],
    body: [
      ['Annual Rainfall', `${input.rainfall} mm`],
      ['Roof Area', `${result.roofAreaM2} m² (${Math.round(result.roofAreaM2 * 10.7639)} sq.ft)`],
      ['Harvestable Rainwater', `${result.harvestedLitres.toLocaleString('en-IN')} litres/year`],
      ['Recommended Storage Tank', `${result.storageTankL.toLocaleString('en-IN')} litres`],
      ['Recharge Structure', result.rechargeStructure],
      ['Recharge Pits', result.numRechargePits > 0 ? `${result.numRechargePits} × (${result.rechargePitDim})` : 'Not recommended'],
      ['Filter Unit', result.filterType],
      ['Down-pipe Diameter', `${result.pipeDiaMm} mm`],
      ['Estimated Annual Water Savings', `Rs ${result.annualSavings.toLocaleString('en-IN')}`],
    ],
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 200 } },
  })
  y = d.lastAutoTable.finalY + 24

  section(d, 'Estimated Installation Cost', y); y += 8
  autoTable(d, {
    startY: y,
    theme: 'grid',
    headStyles: { fillColor: TEAL, textColor: 255, fontSize: 10 },
    styles: { fontSize: 10, cellPadding: 5 },
    head: [['Item', 'Cost (Rs)']],
    body: result.cost.items.map((i) => [i.item, i.cost.toLocaleString('en-IN')]),
    foot: [['Total Estimated Cost', 'Rs ' + result.cost.total.toLocaleString('en-IN')]],
    footStyles: { fillColor: DARK, textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right' } },
  })
  y = d.lastAutoTable.finalY + 20

  if (result.paybackYears > 0) {
    d.setFontSize(10); d.setTextColor(...DARK)
    d.text(`Estimated simple payback period: ${result.paybackYears} years`, 40, y)
    y += 24
  }

  // Footer / disclaimer
  d.setFontSize(8); d.setTextColor(120)
  const disc = 'Disclaimer: Estimates are indicative, based on district-level rainfall normals and standard runoff coefficients. Actual yields, structures and costs vary with site conditions. Consult a certified RWH professional before implementation.'
  d.text(d.splitTextToSize(disc, W - 80), 40, Math.min(y, 780))
  d.setTextColor(...TEAL); d.setFontSize(9)
  d.text('Generated by RWH Assess TN', 40, 815)

  const fname = `RWH_Report_${(input.propertyName || input.district || 'assessment').replace(/\s+/g, '_')}.pdf`
  d.save(fname)
}

function section(d, title, y) {
  d.setFont('helvetica', 'bold'); d.setFontSize(13); d.setTextColor(...TEAL)
  d.text(title, 40, y)
  d.setDrawColor(...TEAL); d.setLineWidth(1.5)
  d.line(40, y + 5, 120, y + 5)
  d.setTextColor(...DARK)
}
